export const EXPLORE_DATA = {
  'Tanger-Tétouan-Al Hoceïma': {
    cities: {
      slides: [
        {
          id: 1,
          name: 'Tanger',
          location: 'Tanger-Tétouan-Al Hoceïma',
          description: 'Porte de l\'Afrique, ville cosmopolite au détroit de Gibraltar',
          image: 'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=600&h=400&fit=crop',
          rating: 4.5,
          isFavorite: false,
          type: 'cities',
          subType: 'coastal',
          contact: 'Tourisme Tanger: +212 539 94 80 80',
          ecotips: 'Utilisez les transports en commun pour réduire l\'empreinte carbone.',
          reviews: ['Magnifique vue sur la mer!', 'Ville historique riche.'],
          photos: ['https://example.com/photo1.jpg', 'https://example.com/photo2.jpg'],
          videos: ['https://example.com/video1.mp4']
        },
        {
          id: 2,
          name: 'Chefchaouen',
          location: 'Tanger-Tétouan-Al Hoceïma',
          description: 'La Perle Bleue du Rif, ville aux ruelles azurées',
          image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600&h=400&fit=crop',
          rating: 4.9,
          isFavorite: true,
          type: 'cities',
          subType: 'mountain',
          contact: 'Office de Tourisme Chefchaouen: +212 539 98 63 43',
          ecotips: 'Respectez les sentiers de randonnée pour préserver la nature.',
          reviews: ['Atmosphère magique!', 'Endroit paisible.'],
          photos: ['https://example.com/photo3.jpg'],
          videos: ['https://example.com/video2.mp4']
        },
        {
          id: 3,
          name: 'Tétouan',
          location: 'Tanger-Tétouan-Al Hoceïma',
          description: 'Ville andalouse aux influences espagnoles',
          image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=400&fit=crop',
          rating: 4.4,
          isFavorite: false,
          type: 'cities',
          subType: 'cultural',
          contact: 'Municipalité de Tétouan: +212 539 97 00 00',
          ecotips: 'Recyclez vos déchets pour un environnement propre.',
          reviews: ['Architecture superbe.', 'Cuisine délicieuse.'],
          photos: ['https://example.com/photo4.jpg'],
          videos: []
        },
        {
          id: 4,
          name: 'Al Hoceïma',
          location: 'Tanger-Tétouan-Al Hoceïma',
          description: 'Station balnéaire sur la côte méditerranéenne',
          image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
          rating: 4.3,
          isFavorite: false,
          type: 'cities',
          subType: 'coastal',
          contact: 'Office de Tourisme Al Hoceïma: +212 539 98 00 00',
          ecotips: 'Évitez les plastiques à usage unique sur les plages.',
          reviews: ['Plages magnifiques.', 'Endroit relaxant.'],
          photos: ['https://example.com/photo5.jpg'],
          videos: ['https://example.com/video3.mp4']
        }
      ],
      suggestions: [
        {
          id: 5,
          name: 'Larache',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.2,
          image: 'https://images.unsplash.com/photo-1568632234157-ce7aecd03d0d?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Ville historique au bord de l\'Atlantique',
          type: 'cities',
          subType: 'coastal',
          contact: 'Municipalité de Larache: +212 539 91 00 00',
          ecotips: 'Utilisez des vélos pour explorer.',
          reviews: ['Histoire fascinante.'],
          photos: [],
          videos: []
        },
        {
          id: 6,
          name: 'Fnideq',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.1,
          image: 'https://images.unsplash.com/photo-1624571395775-253d9666612b?w=400&h=300&fit=crop',
          isFavorite: true,
          description: 'Ville frontalière avec l\'Espagne',
          type: 'cities',
          subType: 'border',
          contact: 'Office de Tourisme Fnideq: +212 539 99 00 00',
          ecotips: 'Respectez les zones protégées.',
          reviews: ['Vue imprenable.'],
          photos: ['https://example.com/photo6.jpg'],
          videos: []
        },
        {
          id: 7,
          name: 'Martil',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.0,
          image: 'https://images.unsplash.com/photo-1581539251075-5c9c55e18c9b?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Station balnéaire familiale',
          type: 'cities',
          subType: 'coastal',
          contact: 'Municipalité de Martil: +212 539 92 00 00',
          ecotips: 'Ramassez les déchets sur la plage.',
          reviews: ['Idéal pour les familles.'],
          photos: [],
          videos: ['https://example.com/video4.mp4']
        },
        {
          id: 8,
          name: 'Ouezzane',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.3,
          image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Ville spirituelle avec des mausolées',
          type: 'cities',
          subType: 'spiritual',
          contact: 'Office de Tourisme Ouezzane: +212 539 93 00 00',
          ecotips: 'Plantez des arbres locaux.',
          reviews: ['Lieu sacré paisible.'],
          photos: ['https://example.com/photo7.jpg'],
          videos: []
        }
      ]
    },
    crafts: {
      slides: [
        {
          id: 9,
          name: 'Tapis Rifains',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.8,
          image: 'https://tse4.mm.bing.net/th/id/OIP.G2p_2zcrDK7OeUi7Pfpm3gHaHa?w=400&h=300&fit=crop',
          isFavorite: true,
          description: 'Tissage artisanal traditionnel du Rif',
          category: 'Textile',
          type: 'crafts',
          subType: 'textile',
          contact: 'Coopérative Tapis Rif: +212 539 98 12 34',
          ecotips: 'Utilisez des teintures naturelles.',
          reviews: ['Qualité exceptionnelle.', 'Art ancestral.'],
          photos: ['https://example.com/photo8.jpg'],
          videos: ['https://example.com/video5.mp4']
        },
        {
          id: 10,
          name: 'Poterie de Tétouan',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.6,
          image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Céramique andalouse traditionnelle',
          category: 'Céramique',
          type: 'crafts',
          subType: 'ceramic',
          contact: 'Atelier Poterie Tétouan: +212 539 97 56 78',
          ecotips: 'Recyclez l\'argile.',
          reviews: ['Beau design.', 'Très durable.'],
          photos: [],
          videos: []
        },
        {
          id: 11,
          name: 'Broderie Rifaine',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.7,
          image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Broderie manuelle des femmes rifaines',
          category: 'Textile',
          type: 'crafts',
          subType: 'textile',
          contact: 'Association Broderie Rif: +212 539 99 87 65',
          ecotips: 'Utilisez des fils recyclés.',
          reviews: ['Détails exquis.', 'Héritage culturel.'],
          photos: ['https://example.com/photo9.jpg'],
          videos: []
        },
        {
          id: 12,
          name: 'Cuir de Tanger',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.5,
          image: 'https://tse4.mm.bing.net/th/id/OIP.F2xQ8YmfAloC-nB4Mbag8AHaEx?w=400&h=300&fit=crop',
          isFavorite: true,
          description: 'Maroquinerie traditionnelle',
          category: 'Maroquinerie',
          type: 'crafts',
          subType: 'leather',
          contact: 'Tanneries Tanger: +212 539 94 32 10',
          ecotips: 'Traitez l\'eau des tanneries.',
          reviews: ['Qualité premium.', 'Style unique.'],
          photos: [],
          videos: ['https://example.com/video6.mp4']
        }
      ],
      suggestions: [
        {
          id: 13,
          name: 'Bijoux Berbères',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.4,
          image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Argenterie et bijoux traditionnels',
          category: 'Bijouterie',
          type: 'crafts',
          subType: 'jewelry',
          contact: 'Atelier Bijoux Berbères: +212 539 95 43 21',
          ecotips: 'Utilisez des métaux recyclés.',
          reviews: ['Pièces uniques.'],
          photos: ['https://example.com/photo10.jpg'],
          videos: []
        },
        {
          id: 14,
          name: 'Sculpture sur Bois',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.3,
          image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop',
          isFavorite: true,
          description: 'Artisanat en bois du Rif',
          category: 'Bois',
          type: 'crafts',
          subType: 'wood',
          contact: 'Coopérative Bois Rif: +212 539 96 54 32',
          ecotips: 'Utilisez du bois durable.',
          reviews: ['Beau travail.'],
          photos: [],
          videos: ['https://example.com/video7.mp4']
        },
        {
          id: 15,
          name: 'Zellige Local',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.6,
          image: 'https://images.unsplash.com/photo-1581539251075-5c9c55e18c9b?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Mosaïque artisanale',
          category: 'Céramique',
          type: 'crafts',
          subType: 'ceramic',
          contact: 'Atelier Zellige: +212 539 97 65 43',
          ecotips: 'Économisez l\'eau.',
          reviews: ['Art marocain classique.'],
          photos: ['https://example.com/photo11.jpg'],
          videos: []
        },
        {
          id: 16,
          name: 'Tissage Traditionnel',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.5,
          image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Tissage manuel de tissus',
          category: 'Textile',
          type: 'crafts',
          subType: 'textile',
          contact: 'Coopérative Tissage: +212 539 98 76 54',
          ecotips: 'Utilisez des fibres naturelles.',
          reviews: ['Douceur incomparable.'],
          photos: [],
          videos: []
        }
      ]
    },
    eco: {
      slides: [
        {
          id: 17,
          name: 'Randonnée Rif',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.9,
          image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&h=300&fit=crop',
          isFavorite: true,
          description: 'Trekking écologique dans les montagnes',
          category: 'Nature',
          type: 'eco',
          subType: 'nature',
          contact: 'Guide Randonnée Rif: +212 539 99 12 34',
          ecotips: 'Restez sur les sentiers pour éviter l\'érosion.',
          reviews: ['Paysages époustouflants.', 'Aventure inoubliable.'],
          photos: ['https://example.com/photo12.jpg'],
          videos: ['https://example.com/video8.mp4']
        },
        {
          id: 18,
          name: 'Coopérative Olive',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.7,
          image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Production durable d\'huile d\'olive bio',
          category: 'Agriculture',
          type: 'eco',
          subType: 'agriculture',
          contact: 'Coopérative Olive: +212 539 98 56 78',
          ecotips: 'Utilisez des méthodes biologiques.',
          reviews: ['Huile de qualité.', 'Projet communautaire.'],
          photos: [],
          videos: []
        },
        {
          id: 19,
          name: 'Éco-Lodge Méditerranée',
          location: 'Tanger-Tétouan-Al Hoceïma',
          rating: 4.8,
          image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop',
          isFavorite: false,
          description: 'Hébergement solaire près de la côte',
          category: 'Hébergement',
          type: 'eco',
          subType: 'accommodation',
          contact: 'Éco-Lodge Méditerranée: +212 539 97 89 01',
          ecotips: 'Énergie solaire renouvelable.',
          reviews: ['Séjour relaxant.', 'Respectueux de l\'environnement.'],
          photos: ['https://example.com/photo13.jpg'],
          videos: []
        },
      ]
    },
  },
}