import type { ExploreItem } from '../types/explore';

export const MOCK_FAVORITES: ExploreItem[] = [
  {
    id: 1,
    name: 'Marrakech',
    location: 'Marrakech-Safi',
    description: 'La Perle du Sud, ville impériale',
    image: 'https://images.unsplash.com/photo-1543418219-44e30b057ffe?w=600&h=400&fit=crop',
    rating: 4.8,
    isFavorite: true,
    type: 'cities',
    subType: 'imperial',
  },
  {
    id: 2,
    name: 'Chefchaouen',
    location: 'Tanger-Tétouan',
    description: 'La Perle Bleue du Rif',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600&h=400&fit=crop',
    rating: 4.9,
    isFavorite: true,
    type: 'cities',
    subType: 'mountain',
  },
  {
    id: 3,
    name: 'Poterie de Safi',
    location: 'Safi',
    description: 'Céramique traditionnelle bleue',
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400&h=300&fit=crop',
    rating: 4.7,
    isFavorite: true,
    type: 'crafts',
    subType: 'ceramic',
    category: 'Céramique',
  },
  {
    id: 4,
    name: 'Éco-lodge Sahara',
    location: 'Merzouga',
    description: 'Hébergement solaire dans le désert',
    image: 'https://www.ecolodge-palmeraie-ouarzazate.com/wp/wp-content/uploads/2024/05/ECOLODGE-PALMERAIE-OUARZAZATE-MAROC-LODGE-AFRICAIN-1030x686.jpg',
    rating: 4.8,
    isFavorite: true,
    type: 'eco',
    subType: 'accommodation',
    category: 'Hébergement',
  },
  {
    id: 5,
    name: 'Tapis Berbères',
    location: 'Moyen Atlas',
    description: 'Tissage artisanal ancestral',
    image: 'https://tse4.mm.bing.net/th/id/OIP.G2p_2zcrDK7OeUi7Pfpm3gHaHa?w=400&h=300&fit=crop',
    rating: 4.8,
    isFavorite: true,
    type: 'crafts',
    subType: 'textile',
    category: 'Textile',
  },
  {
    id: 6,
    name: 'Essaouira',
    location: 'Marrakech-Safi',
    description: 'Ville côtière fortifiée',
    image: 'https://images.unsplash.com/photo-1570618424309-38b4ff52c558?w=600&h=400&fit=crop',
    rating: 4.6,
    isFavorite: true,
    type: 'cities',
    subType: 'coastal',
  },
];